### PR TITLE
Add UART support

### PR DESCRIPTION
**Pull request by caternuson**
For #41 

**BREAKING CHANGE**

- Adds UART support
- Classes refactored into base and I2C/UART specific subs
- examples updated

Tested on Itsy M4.

bno_uart_test

```python
Adafruit CircuitPython 5.1.0 on 2020-04-02; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import board
>>> import adafruit_bno055
>>> bno = adafruit_bno055.BNO055_UART(board.UART())
>>> bno.acceleration
(0.12, -0.43, 9.99)
>>> bno.acceleration
(0.06, -8.53, 5.27)
>>> bno.acceleration
(-3.65, 8.36, 1.48)
>>> bno.acceleration
(-8.49, -4.86, -1.55)
>>> 
```

### CODE REVIEW

**Comment by caternuson** [comment]
Yah, probably good idea to have something. How about commented out code in the existing `bno055_simpletest.py` ?

**Comment by makermelissa** [comment]
Yeah, that would work.

**Comment by makermelissa** [comment]
Just needs to be Black formatted and you're good.

**Comment by makermelissa** [comment]
Looks good

**Comment by madewhatnow** [comment]
Can't wait for the merge!

**Pull request merged**
