### PR TITLE
Rename .reset ._reset as per issue #28

### PR DESCRIPTION
**Pull request by peterhinch**
Implement name change as approved solution to issue #28.

### CODE REVIEW

**Comment by ladyada** [comment]
@peterhinch hiya to check did you try running this code or this is a blind-fix?

**Comment by peterhinch** [comment]
Unfortunately I have no hardware capable of running CircuitPython (Scott Shawcroft has promised to send me some). Until this arrives I have to rely on others to test these PR's. FWIW I can see no further problems with this driver.

**Comment by tannewt** [comment]
@peterhinch I'm waiting to get an email from you. (scott@adafruit.com) If you sent one please follow up. I must have missed it.

**Comment by peterhinch** [comment]
My first email must have ended up in the great /dev/null. I've sent another.

**Comment by peterhinch** [comment]
Hardware with CircuitPython now arrived (thanks, guys).

@ladyada I've now tested this by running **bno055_simpletest.py** successfully.

**Comment by ladyada** [comment]
awesome thank you :)

**Pull request merged**
