### PR TITLE
Add calibration offsets and radii as properties on BNO055 library

### PR DESCRIPTION
**Pull request by sjirwin**
issue #21 

builds on work by @katlings and replaces [her PR](https://github.com/adafruit/Adafruit_CircuitPython_BNO055/pull/22)
implements the approach suggested by @deshipu and addresses feedback from @caternuson

note - assignment is fighting against BNO055 auto-calibration so can have odd behavior

```
Adafruit CircuitPython 4.0.0-rc.1 on 2019-04-23; Adafruit Feather M4 Express with samd51j19
>>> import board, busio
>>> import adafruit_bno055 as bno055
>>> i2c = busio.I2C(board.SCL, board.SDA)
>>> bno = bno055.BNO055(i2c)
>>> bno.radius_magnetometer
0
>>> bno.radius_magnetometer = 40
>>> bno.radius_magnetometer = 40
>>> bno.radius_magnetometer
1
>>> bno.radius_magnetometer
0
>>> bno.offsets_accelerometer = 1, -1, 1
>>> bno.offsets_accelerometer
(1, -1, 1)
```

### CODE REVIEW

**Comment by caternuson** [comment]
> note - assignment is fighting against BNO055 auto-calibration so can have odd behavior

I think that has to do with running in one of the "sensor fusion" modes, like NDOF.

bno055_1
bno055_2

The previous driver didn't do any checking for current mode. Not sure if that's worth adding here?

**Comment by dherrada** [comment]
@caternuson this seems like something useful, as long as the auto-calibration doesn't mess with it. Is this something we should see about merging or close?

**Comment by caternuson** [comment]
Maybe have it as a follow on PR, with a new issue for tracking, just so we can get this PR closed off.

**Comment by kattni** [comment]
@caternuson Are you able to test this if you have not already?

**Comment by caternuson** [comment]
@kattni I didn't test this. Looks like that was notionally done in first post above. I can if you want me to though. In general, I'm OK with this once it passes travis. I think that's where things stalled.

**Comment by kattni** [comment]
@tannewt Can you please approve these changes if you're satisfied? Thanks!

**Pull request merged**
