### PR TITLE
Temp example fix

### PR DESCRIPTION
**Pull request by dherrada**
Same as #64 except it does it at the example level.

### CODE REVIEW

**Comment by dherrada** [comment]
@ladyada Thoughts on adding pointless-string-statement to the globally disabled pylint checks? 

See: https://github.com/PyCQA/pylint/issues/2864
Also: https://twitter.com/gvanrossum/status/112670605505077248

**Comment by ladyada** [comment]
yep ok to add that pylint exception

**Comment by dherrada** [comment]
@ladyada Ok. Just added. Btw, I have tested both the modified examples on a Raspberry Pi.

**Review by ladyada — APPROVED** [review]

**Comment by tannewt** [comment]
Instead of changing the lint settings please use `#` to comment out lines of code.

**Comment by tannewt** [comment]
Please undo the lint settings changes and consult with me before doing something that widespread.

**Comment by ladyada** [comment]
@tannewt kk i approved it, i often use "'s  for multiline comments!

**Comment by dherrada** [comment]
@ladyada Should I revert the .pylintrc change?

**Comment by ladyada** [comment]
yah go for it

**Pull request merged**
